[package]
name = "pound"
version = "0.1.0"
authors = ["Usama Ali"]
license = "Unlicensed"
repository = "https://github.com/Ali-Usama/pound"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.0"